/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.rogerio.app;

import br.com.rogerio.model.Aviao;
import br.com.rogerio.model.FilaAviao;
import br.com.rogerio.enumeration.Enumaviao;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author roger
 */
public class FilaAviaoView extends javax.swing.JFrame {

    FilaAviao filaAux;
    FilaAviao fila;
    Aviao aviao;

    /**
     * Creates new form FilaAviaoView
     */
    public FilaAviaoView() {
        initComponents();

        filaAux = new FilaAviao(5);
        fila = new FilaAviao(5);
        jComboBoxAvioes.removeAllItems();
        jComboBoxAvioes.addItem("< Selecione a Empresa de Aviação >");
        for (Enumaviao aviao : Enumaviao.values()) {
            jComboBoxAvioes.addItem(aviao.toString());
        }
        try {
            adicionarEventoswCombboxAvioes();

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());

        }
    }

    private void adicionarEventoswCombboxAvioes() throws Exception {
        //adiciona um desparador de eventos, ou literalmente o evento
        jComboBoxAvioes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAvioesActionPerformed(evt);
            }
        });
    }

    // este é ação do evento em si 
    private void jComboBoxAvioesActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            preencherFormulario();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    private void validaCombo(){
        
    }

    private void preencherFormulario() throws Exception {
        if (jComboBoxAvioes.getSelectedIndex() > 0) {
            jTextFieldEmpresa.setText(jComboBoxAvioes.getSelectedItem().toString());
            jTextFieldNumero.setText(jComboBoxAvioes.getSelectedIndex() + "");

        } else {
            throw new Exception("Seleção inválida! Selecione uma empresa válida!");
        }
    }

    private void limpaCampos() {
        jTextFieldEmpresa.requestFocus();
        jTextFieldEmpresa.setText("");
        jTextFieldNumero.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFilaAviao = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonTamanhoDaFila = new javax.swing.JButton();
        jButtonRetirarDecolando = new javax.swing.JButton();
        jButtonInserirAviao = new javax.swing.JButton();
        jButtonListaTodosAvioes = new javax.swing.JButton();
        jButtonListaCaracteristicasdoPrimeiroAviaoDaFila = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSaida = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldEmpresa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jComboBoxAvioes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Projeto Fila Exercicio 02 Aeroporto");
        setResizable(false);

        jLabel1.setText("Controle da Pista do Aeroporto");

        jButtonTamanhoDaFila.setText("Nº de Aviões na Pista");
        jButtonTamanhoDaFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTamanhoDaFilaActionPerformed(evt);
            }
        });

        jButtonRetirarDecolando.setText("Autorizar Decolagem");
        jButtonRetirarDecolando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetirarDecolandoActionPerformed(evt);
            }
        });

        jButtonInserirAviao.setText("Adicionar Avião");
        jButtonInserirAviao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirAviaoActionPerformed(evt);
            }
        });

        jButtonListaTodosAvioes.setText("Listar Todos Aviões");
        jButtonListaTodosAvioes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListaTodosAvioesActionPerformed(evt);
            }
        });

        jButtonListaCaracteristicasdoPrimeiroAviaoDaFila.setText("Listar Carac. 1º Avião");
        jButtonListaCaracteristicasdoPrimeiroAviaoDaFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListaCaracteristicasdoPrimeiroAviaoDaFilaActionPerformed(evt);
            }
        });

        jTextAreaSaida.setColumns(20);
        jTextAreaSaida.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSaida);

        jLabel2.setText("Empresa:");

        jLabel3.setText("Número:");

        jComboBoxAvioes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelFilaAviaoLayout = new javax.swing.GroupLayout(jPanelFilaAviao);
        jPanelFilaAviao.setLayout(jPanelFilaAviaoLayout);
        jPanelFilaAviaoLayout.setHorizontalGroup(
            jPanelFilaAviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilaAviaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFilaAviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFilaAviaoLayout.createSequentialGroup()
                        .addGroup(jPanelFilaAviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxAvioes, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFilaAviaoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFilaAviaoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelFilaAviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFilaAviaoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(206, 206, 206))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFilaAviaoLayout.createSequentialGroup()
                                .addGroup(jPanelFilaAviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonRetirarDecolando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonTamanhoDaFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonInserirAviao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonListaTodosAvioes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonListaCaracteristicasdoPrimeiroAviaoDaFila))
                                .addGap(22, 22, 22))))
                    .addGroup(jPanelFilaAviaoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelFilaAviaoLayout.setVerticalGroup(
            jPanelFilaAviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFilaAviaoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxAvioes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanelFilaAviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanelFilaAviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelFilaAviaoLayout.createSequentialGroup()
                        .addComponent(jButtonTamanhoDaFila)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRetirarDecolando)
                        .addGap(19, 19, 19)
                        .addComponent(jButtonInserirAviao)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonListaTodosAvioes)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonListaCaracteristicasdoPrimeiroAviaoDaFila))
                    .addComponent(jScrollPane1))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFilaAviao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFilaAviao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTamanhoDaFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTamanhoDaFilaActionPerformed
        // TODO add your handling code here:
        try {
            jTextAreaSaida.setText("Número de aviões na pista 01: " + fila.size() + "\n"
                    + "Número de aviões na pista 02: " + filaAux.size());

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }

    }//GEN-LAST:event_jButtonTamanhoDaFilaActionPerformed

    private void jButtonRetirarDecolandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetirarDecolandoActionPerformed
        // TODO add your handling code here:
        try {
            jTextAreaSaida.setText("Decolando o avião da empresa: " + fila.peek().getEmpresa());
            fila.dequeue();

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }

    }//GEN-LAST:event_jButtonRetirarDecolandoActionPerformed

    private void jButtonInserirAviaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirAviaoActionPerformed
        // TODO add your handling code here:
        try {
            preencherFormulario();
            aviao = new Aviao();
            aviao.setEmpresa(jTextFieldEmpresa.getText());
            aviao.setNumero(Integer.parseInt(jTextFieldNumero.getText()));
            fila.enqueue(aviao);
            jTextAreaSaida.setText(aviao + "\nAdicionado à fila de aviões do aeroporto!\n");
            limpaCampos();

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonInserirAviaoActionPerformed

    private void jButtonListaTodosAvioesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListaTodosAvioesActionPerformed
        // TODO add your handling code here:
        try {
            jTextAreaSaida.setText("----- Lista de aviões na pista do aeroporto -----:\n");
            while (!fila.isEmpty()) {
                filaAux.enqueue(fila.peek());
                jTextAreaSaida.setText(jTextAreaSaida.getText() + "\n" + fila.peek());
                fila.dequeue();
            }
            while (!filaAux.isEmpty()) {
                fila.enqueue(filaAux.peek());
                filaAux.dequeue();
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonListaTodosAvioesActionPerformed

    private void jButtonListaCaracteristicasdoPrimeiroAviaoDaFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListaCaracteristicasdoPrimeiroAviaoDaFilaActionPerformed
        // TODO add your handling code here:
        try {

            jTextAreaSaida.setText("--- Característica do 1º avião na fila ---\n" + fila.peek());

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonListaCaracteristicasdoPrimeiroAviaoDaFilaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilaAviaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilaAviaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilaAviaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilaAviaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilaAviaoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInserirAviao;
    private javax.swing.JButton jButtonListaCaracteristicasdoPrimeiroAviaoDaFila;
    private javax.swing.JButton jButtonListaTodosAvioes;
    private javax.swing.JButton jButtonRetirarDecolando;
    private javax.swing.JButton jButtonTamanhoDaFila;
    private javax.swing.JComboBox<String> jComboBoxAvioes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelFilaAviao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSaida;
    private javax.swing.JTextField jTextFieldEmpresa;
    private javax.swing.JTextField jTextFieldNumero;
    // End of variables declaration//GEN-END:variables
}
